import { test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

import { DIALS, KEYS, PLUGIN_UUID, uuidOf } from "../src/core/catalog.ts";
import { planRequest } from "../src/core/dispatch.ts";
import { emptyState } from "../src/core/state.ts";

const manifest = JSON.parse(
  readFileSync("com.agentglass.controller.sdPlugin/manifest.json", "utf8"),
) as { Actions: { UUID: string; Name: string; Controllers: string[]; States: unknown[]; Encoder?: unknown }[] };

/**
 * The manifest is generated from the catalog, but it is generated by a script
 * someone has to remember to run — and the SDK's failure mode for a mismatch is
 * a thrown error at *startup*, on the device, which is a slow way to find out.
 * This is the check that makes a stale manifest a failed build instead.
 */
test("every catalog action is in the committed manifest", () => {
  const inManifest = new Set(manifest.Actions.map((a) => a.UUID));
  for (const def of [...KEYS, ...DIALS]) {
    assert.ok(
      inManifest.has(uuidOf(def.id)),
      `${def.id} is missing from the manifest — run \`npm run manifest\``,
    );
  }
});

test("the manifest has nothing the catalog doesn't", () => {
  const inCatalog = new Set([...KEYS, ...DIALS].map((d) => uuidOf(d.id)));
  for (const a of manifest.Actions) {
    assert.ok(inCatalog.has(a.UUID), `${a.UUID} is in the manifest but not the catalog`);
  }
});

test("keys are keypad actions and dials are encoders", () => {
  const byUuid = new Map(manifest.Actions.map((a) => [a.UUID, a]));
  for (const def of KEYS) assert.deepEqual(byUuid.get(uuidOf(def.id))!.Controllers, ["Keypad"]);
  for (const def of DIALS) {
    const a = byUuid.get(uuidOf(def.id))!;
    assert.deepEqual(a.Controllers, ["Encoder"]);
    assert.ok(a.Encoder, `${def.id} needs an Encoder block for its touch strip`);
  }
});

test("ids and names are unique — two rows sharing either is a silent collision", () => {
  const all = [...KEYS, ...DIALS];
  assert.equal(new Set(all.map((d) => d.id)).size, all.length, "duplicate id");
  assert.equal(new Set(all.map((d) => d.name)).size, all.length, "duplicate name");
});

test("every key is labelled and documented", () => {
  for (const def of [...KEYS, ...DIALS]) {
    assert.ok(def.label.trim().length > 0, `${def.id} has no label`);
    assert.ok(def.tooltip.trim().length > 0, `${def.id} has no tooltip`);
  }
});

test("uuids are namespaced under the plugin", () => {
  assert.equal(uuidOf("view.git"), `${PLUGIN_UUID}.view.git`);
});

/**
 * Every plain command key must actually resolve to a request. A row with a
 * `command` behaviour and no `action` would install fine, look fine, and do
 * nothing when pressed.
 */
test("every command key dispatches a real request", () => {
  for (const def of KEYS.filter((d) => d.behaviour === "command")) {
    assert.ok(def.action, `${def.id} is a command key with no action`);
    const plan = planRequest(def.action!, emptyState());
    assert.ok(plan, `${def.id} does not plan a request`);
    assert.equal(plan!.path, "/control");
  }
});

test("the approve and deny keys target the gate endpoint", () => {
  const state = { gates: [{ id: "g1", tool_name: "Bash" }], selected: 0 };
  for (const id of ["approve", "deny"]) {
    const def = KEYS.find((d) => d.id === id)!;
    const plan = planRequest(def.action!, state);
    assert.equal(plan!.path, "/gate/decide", `${id} must decide a gate, not navigate`);
    assert.equal((plan!.body as { id: string }).id, "g1");
  }
});

test("the keys that only read state carry no action", () => {
  for (const def of KEYS.filter((d) => ["usage-5h", "usage-week", "link", "gate-next", "gate-prev"].includes(d.behaviour))) {
    assert.equal(def.action, undefined, `${def.id} should not dispatch anything`);
  }
});

/** Everything a dial does has to be reachable without one. */
test("no dial is the only way to do its job", () => {
  const behaviours = new Set(KEYS.map((d) => d.behaviour));
  const commands = KEYS.filter((d) => d.action).map((d) => JSON.stringify(d.action));

  assert.ok(behaviours.has("approve"), "the gate dial's press needs an Approve key");
  assert.ok(behaviours.has("gate-next") && behaviours.has("gate-prev"), "its rotation needs Next/Prev keys");
  for (const dir of [1, -1]) {
    assert.ok(commands.includes(JSON.stringify({ kind: "theme", dir })), `theme dir ${dir} needs a key`);
    assert.ok(commands.includes(JSON.stringify({ kind: "zoom", dir })), `zoom dir ${dir} needs a key`);
  }
  assert.ok(commands.includes(JSON.stringify({ kind: "zoom", dir: 0 })), "the zoom dial's press needs a reset key");
});

/** The whole point of "all the options in button form". */
test("every control command agentglass accepts has a key", () => {
  // approve/deny plan nothing against an empty queue by design, so they drop
  // out here; their own keys are covered by the dial-parity test above.
  const commands = new Set(
    KEYS.filter((d) => d.action)
      .map((d) => planRequest(d.action!, emptyState()))
      .filter((p) => p !== null)
      .map((p) => JSON.stringify(p!.body)),
  );
  const expected = [
    ...["git", "diff", "pr", "docker", "term", "chat"].map((to) => ({ cmd: "view", to })),
    ...["stats", "skills", "search", "help", "palette"].map((what) => ({ cmd: "open", what })),
    { cmd: "workspace" },
    { cmd: "esc" },
    { cmd: "theme", dir: 1 },
    { cmd: "theme", dir: -1 },
    { cmd: "zoom", dir: 1 },
    { cmd: "zoom", dir: -1 },
    { cmd: "zoom", dir: 0 },
    { cmd: "chat", do: "new" },
    { cmd: "chat", do: "compact" },
  ];
  for (const body of expected) {
    assert.ok(commands.has(JSON.stringify(body)), `no key sends ${JSON.stringify(body)}`);
  }
});
