/**
 * Every button the plugin offers, in one table.
 *
 * This is the single source of truth for three things that used to drift apart:
 * the manifest's `Actions` array (generated by scripts/make-manifest.mjs), the
 * placeholder icons in the OpenDeck action list (scripts/make-icons.mjs), and
 * the runtime behaviour (src/actions/keys.ts builds one action object per row).
 * Adding a button means adding a row here and rebuilding — there is no second
 * list to remember.
 *
 * Why one action per command rather than a handful of keys with dropdowns: on
 * a deck you are dragging a *thing you want on a key*, and "Command → open the
 * inspector → pick 'diff' from a select" is three steps to express something
 * the action list could have just offered. The inspector is now only for
 * settings that genuinely vary (the server URL), not for choosing what the key
 * is.
 */

import type { Action } from "./model.ts";
import { METRICS, type MetricId } from "./system.ts";
import type { GlyphId } from "../render/glyphs.ts";
import type { AccentId } from "../render/theme.ts";

export const PLUGIN_UUID = "com.agentglass.controller";

/** What a key does beyond firing its `action`, when that needs live state. */
export type KeyBehaviour =
  /** Fire and forget — the great majority. */
  | "command"
  /** Fires `action`, and repaints with the pending-approval count. */
  | "approve"
  /** Fires `action`; dimmed when the queue is empty. */
  | "deny"
  /** Moves the queue selection instead of calling the server. */
  | "gate-next"
  | "gate-prev"
  /** Draws a usage window; pressing it forces a refresh. */
  | "usage-5h"
  | "usage-week"
  /** Draws link state; pressing it forces a refresh. */
  | "link"
  /** Draws a meter for this machine rather than for agentglass. Named for the
   *  metric it reads, which is what lets the key hand its own behaviour to the
   *  monitor without a lookup table in between. */
  | MetricId;

export type KeyDef = {
  /** Appended to PLUGIN_UUID for the manifest UUID, and used as the icon path. */
  id: string;
  /** How the action reads in OpenDeck's list — grouped by prefix so it sorts well. */
  name: string;
  /** Baked into the key art. Kept short; it is rendered upper-case. */
  label: string;
  glyph: GlyphId;
  accent: AccentId;
  tooltip: string;
  behaviour: KeyBehaviour;
  /** Absent for the keys that only read state (usage, link). */
  action?: Action;
};

const view = (v: "git" | "diff" | "pr" | "docker" | "term" | "chat", label: string, tooltip: string): KeyDef => ({
  id: `view.${v}`,
  name: `View · ${label}`,
  label,
  glyph: v,
  accent: "view",
  tooltip,
  behaviour: "command",
  action: { kind: "view", view: v },
});

const panel = (w: "stats" | "skills" | "search" | "help" | "palette", label: string, tooltip: string): KeyDef => ({
  id: `open.${w}`,
  name: `Panel · ${label}`,
  label,
  glyph: w,
  accent: "panel",
  tooltip,
  behaviour: "command",
  action: { kind: "open", what: w },
});

export const KEYS: KeyDef[] = [
  // --- workspace views ---------------------------------------------------
  view("git", "Git", "Open the git view — status, branches, commits."),
  view("diff", "Diff", "Open the working-tree diff."),
  view("pr", "PRs", "Open the pull request view."),
  view("docker", "Docker", "Open the docker view."),
  // The terminal is a workspace view like the others; this is the key that
  // launches it, and it is named for what you want rather than where it lives.
  { ...view("term", "Terminal", "Launch the cockpit terminal — a real shell in the workspace."), id: "view.term", name: "Launch · Terminal" },
  view("chat", "Chat", "Open the chat view."),

  // --- panels --------------------------------------------------------------
  panel("stats", "Stats", "Open the stats panel."),
  panel("skills", "Skills", "Open the skills catalogue."),
  panel("search", "Search", "Open search."),
  panel("help", "Help", "Open the keyboard help."),
  panel("palette", "Palette", "Open the command palette."),

  // --- frame navigation -----------------------------------------------------
  {
    id: "workspace",
    name: "Nav · Workspace",
    label: "Workspace",
    glyph: "workspace",
    accent: "nav",
    tooltip: "Toggle the workspace overlay.",
    behaviour: "command",
    action: { kind: "workspace" },
  },
  {
    id: "home",
    name: "Nav · Home",
    label: "Home",
    glyph: "home",
    accent: "nav",
    tooltip: "Close whatever is open — the same peel as Escape.",
    behaviour: "command",
    action: { kind: "esc" },
  },

  // --- chat control ----------------------------------------------------------
  {
    id: "chat.new",
    name: "Chat · New session",
    label: "New",
    glyph: "chatNew",
    accent: "chat",
    tooltip: "Start a new chat session in the cockpit.",
    behaviour: "command",
    action: { kind: "chat", do: "new" },
  },
  {
    id: "chat.compact",
    name: "Chat · Compact",
    label: "Compact",
    glyph: "compact",
    accent: "chat",
    tooltip: "Compact the open chat session.",
    behaviour: "command",
    action: { kind: "chat", do: "compact" },
  },

  // --- appearance --------------------------------------------------------------
  {
    id: "theme.next",
    name: "Look · Theme next",
    label: "Theme +",
    glyph: "themeNext",
    accent: "look",
    tooltip: "Step forward through agentglass's themes.",
    behaviour: "command",
    action: { kind: "theme", dir: 1 },
  },
  {
    id: "theme.prev",
    name: "Look · Theme prev",
    label: "Theme −",
    glyph: "themePrev",
    accent: "look",
    tooltip: "Step back through agentglass's themes.",
    behaviour: "command",
    action: { kind: "theme", dir: -1 },
  },
  {
    id: "zoom.in",
    name: "Look · Zoom in",
    label: "Zoom +",
    glyph: "zoomIn",
    accent: "look",
    tooltip: "Zoom the cockpit in.",
    behaviour: "command",
    action: { kind: "zoom", dir: 1 },
  },
  {
    id: "zoom.out",
    name: "Look · Zoom out",
    label: "Zoom −",
    glyph: "zoomOut",
    accent: "look",
    tooltip: "Zoom the cockpit out.",
    behaviour: "command",
    action: { kind: "zoom", dir: -1 },
  },
  {
    id: "zoom.reset",
    name: "Look · Zoom reset",
    label: "Zoom 1:1",
    glyph: "zoomReset",
    accent: "look",
    tooltip: "Reset the cockpit zoom.",
    behaviour: "command",
    action: { kind: "zoom", dir: 0 },
  },

  // --- approvals ----------------------------------------------------------------
  {
    id: "approve",
    name: "Gate · Approve",
    label: "Approve",
    glyph: "approve",
    accent: "go",
    tooltip: "Approve the selected held tool call. Shows the pending count.",
    behaviour: "approve",
    action: { kind: "approve" },
  },
  {
    id: "deny",
    name: "Gate · Deny",
    label: "Deny",
    glyph: "deny",
    accent: "stop",
    tooltip: "Deny the selected held tool call.",
    behaviour: "deny",
    action: { kind: "deny" },
  },
  {
    id: "gate.next",
    name: "Gate · Next",
    label: "Next",
    glyph: "next",
    accent: "alert",
    tooltip: "Select the next held tool call — the dial's job, without a dial.",
    behaviour: "gate-next",
  },
  {
    id: "gate.prev",
    name: "Gate · Previous",
    label: "Prev",
    glyph: "prev",
    accent: "alert",
    tooltip: "Select the previous held tool call.",
    behaviour: "gate-prev",
  },

  // --- instruments -------------------------------------------------------------
  {
    id: "usage.5h",
    name: "Monitor · 5-hour usage",
    label: "5h Window",
    glyph: "stats",
    accent: "meter",
    tooltip: "Anthropic 5-hour rate-limit window: level, trend, and time to reset.",
    behaviour: "usage-5h",
  },
  {
    id: "usage.week",
    name: "Monitor · Weekly usage",
    label: "Weekly",
    glyph: "stats",
    accent: "meter",
    tooltip: "Anthropic 7-day rate-limit window: level, trend, and time to reset.",
    behaviour: "usage-week",
  },
  {
    id: "link",
    name: "Monitor · Link",
    label: "Link",
    glyph: "link",
    accent: "go",
    tooltip: "Is agentglass reachable, and is anything waiting on you.",
    behaviour: "link",
  },

  // --- this machine --------------------------------------------------------------
  // The only keys on the deck that are not about agentglass. An agent that is
  // building, testing and running containers is spending *your* machine, and
  // the cockpit can't see any of it — so these read the computer directly and
  // stay live whether or not agentglass is up.
  {
    id: "sys.cpu",
    name: "Monitor · CPU",
    label: "CPU",
    glyph: "cpu",
    accent: "meter",
    tooltip: "Processor load on this machine, with a minute and a half of trend.",
    behaviour: "cpu",
  },
  {
    id: "sys.gpu",
    name: "Monitor · GPU",
    label: "GPU",
    glyph: "gpu",
    accent: "meter",
    tooltip: "Graphics load on this machine. AMD and Intel via sysfs, NVIDIA via nvidia-smi.",
    behaviour: "gpu",
  },
  {
    id: "sys.ram",
    name: "Monitor · Memory",
    label: "Memory",
    glyph: "ram",
    accent: "meter",
    tooltip: "Memory in use on this machine, against what a new allocation could actually get.",
    behaviour: "ram",
  },
  {
    id: "sys.battery",
    name: "Monitor · Battery",
    label: "Battery",
    glyph: "battery",
    accent: "meter",
    tooltip: "Battery charge on this machine, and whether it is charging.",
    behaviour: "battery",
  },
];

/** Is this key a machine meter — and therefore its own metric id? */
export const isMetric = (b: KeyBehaviour): b is MetricId => (METRICS as readonly string[]).includes(b);

/** The Stream Deck + encoders. Every one of these has key equivalents above, so
 *  a deck without dials loses nothing but the scrubbing feel. */
export type DialDef = {
  id: string;
  name: string;
  label: string;
  glyph: GlyphId;
  accent: AccentId;
  tooltip: string;
  triggers: { Rotate?: string; Push?: string; Touch?: string };
};

export const DIALS: DialDef[] = [
  {
    id: "dial.gate",
    name: "Dial · Approvals",
    label: "Gate",
    glyph: "approve",
    accent: "go",
    tooltip: "Turn to scrub the approval queue, press to approve.",
    triggers: { Rotate: "Select approval", Push: "Approve", Touch: "Approve" },
  },
  {
    id: "dial.theme",
    name: "Dial · Theme",
    label: "Theme",
    glyph: "theme",
    accent: "look",
    tooltip: "Turn to cycle the agentglass theme.",
    triggers: { Rotate: "Cycle theme" },
  },
  {
    id: "dial.zoom",
    name: "Dial · Zoom",
    label: "Zoom",
    glyph: "zoomIn",
    accent: "look",
    tooltip: "Turn to zoom the cockpit, press to reset.",
    triggers: { Rotate: "Zoom", Push: "Reset zoom" },
  },
];

export const uuidOf = (id: string): string => `${PLUGIN_UUID}.${id}`;
